title: Hearty Cooking
description: Easy and nutritious recipes to meal prep.
locale: en

url: "https://hearty.cooking"
logo: /assets/images/hearty-logo-transparent.png

plugins:
  - jekyll-feed

exclude: # items are added to the internal "default list".
  - LICENSE.txt
  - README.md

theme: jekyll-theme-so-simple

author:
  name: Vincent Saelzler
  picture: /assets/images/vince.jpg
